package tchap:websocketserver@0.1.0;

interface types {
    enum message-kind {
        text,
        binary,
    }

    record websocket-message {
        kind: message-kind,
        body: option<list<u8>>,
    }
}

interface web-socket-server {
    use types.{websocket-message};

    handle-message: func(message: websocket-message) -> option<websocket-message>;
}
